version: '3.7'
services:
  consul-server1:
    image: hashicorp/consul:1.14.6
    container_name: consul-server1
    restart: always
    volumes:
     - ./consul_server/server1.json:/consul/config/server1.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul:1.14.6
    container_name: consul-server2
    restart: always
    volumes:
     - ./consul_server/server2.json:/consul/config/server2.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul:1.14.6
    container_name: consul-server3
    restart: always
    volumes:
     - ./consul_server/server3.json:/consul/config/server3.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.14.6
    container_name: consul-client
    restart: always
    volumes:
     - ./consul_server/client.json:/consul/config/client.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent"

  apigateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    image: apigateway
    ports:
      - 8001:8000
    environment:
      - NODE=apigateway
      - PRIMARY=1
      - CONSUL_SERVER=consul-server1
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul-server1
    volumes:
      - ./certs/:/consul/config/certs/:ro
    cap_add:
      - NET_ADMIN
    networks:
      - consul

  countries:
    build:
      context: countries
      dockerfile: Dockerfile
    image: countries
    ports:
      - 8002:8000
    environment:
      - NODE=countries
      - PRIMARY=1
      - CONSUL_SERVER=consul-server1
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul-server1
    volumes:
      - ./certs/:/consul/config/certs/:ro
    cap_add:
      - NET_ADMIN
    networks:
      - consul

  food:
    build:
      context: food
      dockerfile: Dockerfile
    image: food
    ports:
      - 8003:8000
    environment:
      - NODE=food
      - PRIMARY=1
      - CONSUL_SERVER=consul-server1
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul-server1
    volumes:
      - ./certs/:/consul/config/certs/:ro
    cap_add:
      - NET_ADMIN
    networks:
      - consul

networks:
  consul:
    driver: bridge
